from . import auth_router
from . import dashboards_router
from . import projects_router
from . import parcels_router
from . import compensation_router
from . import rehabilitation_router
from . import documents_router
from . import objections_router
from . import risk_router
